# Generated by Django 3.0.7 on 2021-12-11 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(blank=True, max_length=150, null=True)),
                ('author', models.CharField(max_length=100)),
                ('released_date', models.DateField()),
                ('in_stock', models.BooleanField(default=False)),
            ],
        ),
    ]
