# Generated by Django 3.0.7 on 2021-12-13 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_book_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=10),
        ),
    ]
