# Generated by Django 3.0.7 on 2021-12-13 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='conten',
            new_name='content',
        ),
    ]
