# Generated by Django 3.0.7 on 2022-06-08 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='data_posted',
            new_name='date_posted',
        ),
    ]
