# Generated by Django 3.0.7 on 2021-11-23 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20211104_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='inStock',
        ),
        migrations.AddField(
            model_name='products',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
